--- !<io.dekorate.docker.config.EditableDockerBuildConfig>
project:
  root: file:///C:/Users/acasa/IdeaProjects/udemy/Dillip/sample-kubernetes-dekorate/
  dekorateInputDir: null
  dekorateOutputDir: META-INF/dekorate
  dekorateMetaDir: ../.dekorate
  buildInfo:
    name: my-spring-app
    version: 1.0.0
    packaging: jar
    buildTool: maven
    buildToolVersion: 3.6.3
    outputFile: file:///C:/Users/acasa/IdeaProjects/udemy/Dillip/sample-kubernetes-dekorate/target/my-spring-app-1.0.0.jar
    classOutputDir: file:///C:/Users/acasa/IdeaProjects/udemy/Dillip/sample-kubernetes-dekorate/target/classes/
    resourceDir: file:///C:/Users/acasa/IdeaProjects/udemy/Dillip/sample-kubernetes-dekorate/target/classes/
  scmInfo:
    root: file:///C:/Users/acasa/IdeaProjects/udemy/Dillip/sample-kubernetes-dekorate/
    branch: master
    commit: 4fc8410c044a4ea4644188d3066ed24f5a5bd2ac
    remote:
      origin: https://github.com/acasado666/sample-kubernetes-dekorate.git
partOf: null
name: my-spring-app
version: 1.0.0
enabled: true
registry: null
group: acasa
image: null
dockerFile: Dockerfile
autoBuildEnabled: false
autoPushEnabled: false
autoLoadEnabled: false
autoDeployEnabled: false
