---
project:
  root: file:///C:/Users/acasa/IdeaProjects/udemy/Dillip/sample-kubernetes-dekorate/
  dekorateInputDir: null
  dekorateOutputDir: META-INF/dekorate
  dekorateMetaDir: ../.dekorate
  buildInfo:
    name: my-spring-app
    version: 1.0.0
    packaging: jar
    buildTool: maven
    buildToolVersion: 3.6.3
    outputFile: file:///C:/Users/acasa/IdeaProjects/udemy/Dillip/sample-kubernetes-dekorate/target/my-spring-app-1.0.0.jar
    classOutputDir: file:///C:/Users/acasa/IdeaProjects/udemy/Dillip/sample-kubernetes-dekorate/target/classes/
    resourceDir: file:///C:/Users/acasa/IdeaProjects/udemy/Dillip/sample-kubernetes-dekorate/target/classes/
  scmInfo:
    root: file:///C:/Users/acasa/IdeaProjects/udemy/Dillip/sample-kubernetes-dekorate/
    branch: master
    commit: 4fc8410c044a4ea4644188d3066ed24f5a5bd2ac
    remote:
      origin: https://github.com/acasado666/sample-kubernetes-dekorate.git
partOf: null
name: my-spring-app
version: 1.0.0
deploymentKind: Deployment
envVars:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
    secret: ""
    configmap: ""
    field: ""
    resourceField: ""
    prefix: ""
workingDir: null
serviceAccount: null
ports:
  - name: http
    containerPort: 8080
    hostPort: 80
    nodePort: 0
    path: /
    protocol: TCP
serviceType: ClusterIP
imagePullPolicy: IfNotPresent
deploymentStrategy: None
rollingUpdate:
  maxUnavailable: 25%
  maxSurge: 25%
nodeSelector:
  key: ""
  value: ""
livenessProbe:
  httpActionPath: ""
  execAction: ""
  tcpSocketAction: ""
  grpcAction: ""
  initialDelaySeconds: 0
  periodSeconds: 30
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  httpActionPath: ""
  execAction: ""
  tcpSocketAction: ""
  grpcAction: ""
  initialDelaySeconds: 0
  periodSeconds: 30
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3
startupProbe:
  httpActionPath: ""
  execAction: ""
  tcpSocketAction: ""
  grpcAction: ""
  initialDelaySeconds: 0
  periodSeconds: 30
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3
requestResources:
  memory: ""
  cpu: ""
limitResources:
  memory: ""
  cpu: ""
autoDeployEnabled: false
replicas: 2
ingress:
  host: ""
  ingressClassName: ""
  targetPort: http
  expose: false
  tlsSecretName: ""
headless: false
