spring.application.name=my-spring-app
server.port=8080
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

dekorate.kubernetes.name=my-spring-app
dekorate.kubernetes.version=1.0.0
dekorate.kubernetes.replicas=2

dekorate.kubernetes.ports[0].name=http
dekorate.kubernetes.ports[0].container-port=8080

dekorate.kubernetes.env-vars[0].name=SPRING_PROFILES_ACTIVE
dekorate.kubernetes.env-vars[0].value=prod